name: Build Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  itmo-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Java
        run: mvn clean package
      - name: Build Docker image
        run: docker build -t tenders-server .
      - name: Tag Docker image
        run: docker tag tenders-server:latest ${{ secrets.DOCKERHUB_USERNAME }}/tenders-server:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Counter Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/tenders-server:latest